# Generated by Django 4.1.6 on 2023-05-20 19:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('R_P', models.BooleanField(verbose_name='Thu(0)/Chi(1):')),
            ],
        ),
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày Giao Dịch:')),
                ('year', models.SmallIntegerField(editable=False)),
                ('R_P', models.CharField(choices=[('R', 'Thu'), ('P', 'Chi')], max_length=1, verbose_name='Thu/Chi:')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Số Tiền:')),
                ('Description', models.CharField(max_length=150, verbose_name='Diễn giải:')),
                ('Note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ghi Chú:')),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ledger.transactions', verbose_name='Hạng Mục Giao Dịch:')),
            ],
        ),
    ]
