# Generated by Django 4.1.6 on 2023-05-20 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0002_alter_ledger_options_alter_transactions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='Created_Time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='Creator',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
