# Generated by Django 4.1.6 on 2023-05-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_ledger_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='Source',
        ),
        migrations.AddField(
            model_name='ledger',
            name='Sync',
            field=models.BooleanField(default=1, verbose_name='Đồng Bộ:'),
            preserve_default=False,
        ),
    ]
