# Generated by Django 4.1.6 on 2023-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_remove_ledger_source_ledger_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Sync',
            field=models.BooleanField(editable=False, verbose_name='Đồng Bộ:'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='Transaction',
            field=models.CharField(choices=[('A', 'Khách Hàng Trả Tiền'), ('B', 'Thanh Toán Tiền Sợi'), ('C', 'Chi Phí Khác'), ('D', 'Khoản Thu Khác'), ('E', 'Trả Lương Nhân Viên')], max_length=1, verbose_name='Hạng Mục Giao Dịch'),
        ),
    ]
