# Generated by Django 4.1.6 on 2023-05-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_ledger_sync_alter_ledger_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='Sync_address',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
