# Generated by Django 4.1.6 on 2023-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_ledger_sync_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Sync_address',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
