# Generated by Django 4.1.6 on 2023-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_ledger_sync_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='Sync_address',
        ),
        migrations.AddField(
            model_name='ledger',
            name='Address',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='Database',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
