# Generated by Django 4.1.6 on 2023-05-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_remove_ledger_sync_address_ledger_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Address',
            field=models.PositiveBigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='Database',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='Transaction',
            field=models.CharField(choices=[('A', 'Khách Hàng Trả Tiền'), ('B', 'Trả Tiền Sợi'), ('C', 'Chi Phí Khác'), ('D', 'Khoản Thu Khác'), ('E', 'Trả Lương Nhân Viên')], max_length=1, verbose_name='Hạng Mục Giao Dịch'),
        ),
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together={('Database', 'Address')},
        ),
    ]
