# Generated by Django 4.1.6 on 2023-05-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_ledger_address_alter_ledger_database_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Address',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='Database',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
