# Generated by Django 4.1.6 on 2023-05-23 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_alter_ledger_address_alter_ledger_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ledger.transactions', verbose_name='Hạng Mục Giao Dịch'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='R_P',
            field=models.CharField(choices=[('Thu', 'Thu'), ('Chi', 'Chi')], max_length=3, verbose_name='Thu/Chi:'),
        ),
    ]
