# Generated by Django 4.1.6 on 2023-05-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_alter_ledger_transaction_alter_transactions_r_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='R_P',
        ),
    ]
