# Generated by Django 4.1.6 on 2023-05-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_remove_ledger_r_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='Auto_Sync',
            field=models.BooleanField(default=False),
        ),
    ]
