# Generated by Django 4.1.6 on 2023-06-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_transactions_auto_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Database',
            field=models.CharField(editable=False, max_length=20, null=True, verbose_name='Source:'),
        ),
    ]
