# Generated by Django 4.1.6 on 2023-05-19 07:56

import QLSanXuat.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Det_Tay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày:')),
                ('year', models.SmallIntegerField(editable=False)),
                ('Product_name', models.CharField(max_length=20, verbose_name='Tên Hàng:')),
                ('M_per_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Số m/kg:')),
                ('Fit_size', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Khổ Hàng:')),
                ('Spandex_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='% Spandex:')),
                ('BatchNo', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mã Lô:')),
                ('BatchID', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã Lô')),
                ('Quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số Lượng (Cây):')),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Khối Lượng:')),
                ('Note', models.CharField(blank=True, max_length=100, verbose_name='Ghi Chú:')),
                ('Created_Time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '1.1. Dệt Tẩy',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Tên Khách Hàng:')),
                ('real_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tên Khác:')),
                ('Phone_Number', phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Số ĐT:')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa Chỉ:')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:')),
                ('Own', models.BooleanField(default=False, verbose_name='Nội Bộ')),
            ],
            options={
                'verbose_name_plural': '2.3. Khách Hàng',
            },
        ),
        migrations.CreateModel(
            name='KhoCang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KhoCang', models.CharField(max_length=20, unique=True, verbose_name='Lò Căng')),
                ('KyHieu', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Only alphabetic characters are allowed.', regex='^[A-Za-z]*$'), QLSanXuat.models.no_space_or_number_validator], verbose_name='Ký Hiệu:')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa Chỉ')),
                ('OS', models.BooleanField(default=1, verbose_name='Gia Công')),
            ],
            options={
                'verbose_name_plural': '2.7. Lò Căng',
            },
        ),
        migrations.CreateModel(
            name='KhoDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KhoDet', models.CharField(max_length=30, unique=True, verbose_name='Tên Xưởng:')),
                ('KyHieu', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Chỉ Cho Phép Kí Tự Chữ Cái.', regex='^[A-Za-z]*$'), QLSanXuat.models.no_space_or_number_validator], verbose_name='Ký Hiệu:')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa Chỉ:')),
                ('OS', models.BooleanField(default=1, verbose_name='Gia Công')),
            ],
            options={
                'verbose_name_plural': '2.1. Xưởng Dệt',
            },
        ),
        migrations.CreateModel(
            name='KhoIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KhoIn', models.CharField(max_length=20, unique=True, verbose_name='Lò In')),
                ('KyHieu', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Chỉ Cho Phép Kí Tự Chữ Cái.', regex='^[A-Za-z]*$'), QLSanXuat.models.no_space_or_number_validator], verbose_name='Ký Hiệu:')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa Chỉ')),
                ('OS', models.BooleanField(default=1, verbose_name='Gia Công')),
            ],
            options={
                'verbose_name_plural': '2.5. Lò In',
            },
        ),
        migrations.CreateModel(
            name='KhoNhuom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KhoNhuom', models.CharField(max_length=20, unique=True, verbose_name='Lò Nhuộm')),
                ('KyHieu', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Chỉ Cho Phép Kí Tự Chữ Cái.', regex='^[A-Za-z]*$'), QLSanXuat.models.no_space_or_number_validator], verbose_name='Ký Hiệu:')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa Chỉ')),
                ('OS', models.BooleanField(default=1, verbose_name='Gia Công')),
            ],
            options={
                'verbose_name_plural': '2.6. Lò Nhuộm',
            },
        ),
        migrations.CreateModel(
            name='KhoTay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KhoTay', models.CharField(max_length=30, unique=True, verbose_name='Lò Tẩy')),
                ('KyHieu', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Chỉ Cho Phép Kí Tự Chữ Cái.', regex='^[A-Za-z]*$'), QLSanXuat.models.no_space_or_number_validator], verbose_name='Ký Hiệu:')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa Chỉ')),
                ('OS', models.BooleanField(default=1, verbose_name='Gia Công')),
            ],
            options={
                'verbose_name_plural': '2.4. Lò Tẩy',
            },
        ),
        migrations.CreateModel(
            name='Product_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_class', models.CharField(max_length=20, unique=True, verbose_name='Thêm Phân Loại Hàng Mới:')),
            ],
            options={
                'verbose_name_plural': '2.2. Phân Loại Hàng',
            },
        ),
        migrations.CreateModel(
            name='Tay_Nhuom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày:')),
                ('year', models.SmallIntegerField(editable=False)),
                ('BatchNo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Lần Xuất:')),
                ('BatchID', models.CharField(blank=True, max_length=23, unique=True, verbose_name='Mã Lô')),
                ('Qty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số Lượng (Cây):')),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Khối Lượng:')),
                ('Note', models.CharField(blank=True, max_length=100, verbose_name='Ghi Chú:')),
                ('Created_Time', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('Customer', models.ForeignKey(limit_choices_to={'Own': True}, on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khachhang', verbose_name='Khách Hàng:')),
                ('DetTay_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLSanXuat.det_tay', verbose_name='Mã Lô Dệt Tẩy:')),
                ('Dye_Des', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khonhuom', verbose_name='Lò Nhuộm:')),
            ],
            options={
                'verbose_name_plural': '1.4. Tẩy Nhuộm',
            },
        ),
        migrations.CreateModel(
            name='Tay_Moc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày:')),
                ('year', models.SmallIntegerField(editable=False)),
                ('BatchNo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Lần Xuất:')),
                ('BatchID', models.CharField(blank=True, max_length=23, unique=True, verbose_name='Mã Lô')),
                ('Qty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số Lượng (Cây):')),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Khối Lượng:')),
                ('Note', models.CharField(blank=True, max_length=100, verbose_name='Ghi Chú:')),
                ('Created_Time', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người Tạo:')),
                ('Customer', models.ForeignKey(limit_choices_to={'Own': False}, on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khachhang', verbose_name='Khách Hàng:')),
                ('DetTay_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLSanXuat.det_tay', verbose_name='Mã Lô Dệt Tẩy:')),
                ('Print_Des', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khoin', verbose_name='Nơi Đến (In):')),
            ],
            options={
                'verbose_name_plural': '1.2. Tẩy Mộc',
            },
        ),
        migrations.CreateModel(
            name='Tay_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày:')),
                ('year', models.SmallIntegerField(editable=False)),
                ('BatchNo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Lần Xuất:')),
                ('BatchID', models.CharField(blank=True, max_length=23, unique=True, verbose_name='Mã Lô')),
                ('Qty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số Lượng (Cây):')),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Khối Lượng:')),
                ('Note', models.CharField(blank=True, max_length=100, verbose_name='Ghi Chú:')),
                ('Created_Time', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('Customer', models.ForeignKey(limit_choices_to={'Own': True}, on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khachhang', verbose_name='Khách Hàng:')),
                ('DetTay_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLSanXuat.det_tay', verbose_name='Mã Lô Dệt Tẩy:')),
                ('Print_Des', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khoin', verbose_name='Lò In:')),
            ],
            options={
                'verbose_name_plural': '1.3. Tẩy In',
            },
        ),
        migrations.AddField(
            model_name='det_tay',
            name='Destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khotay', verbose_name='Nơi Đến:'),
        ),
        migrations.AddField(
            model_name='det_tay',
            name='FromWhere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khodet', verbose_name='Nơi Đi:'),
        ),
        migrations.AddField(
            model_name='det_tay',
            name='Product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.product_class', verbose_name='Phân Loại:'),
        ),
        migrations.AddField(
            model_name='det_tay',
            name='User_Create',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày:')),
                ('year', models.PositiveSmallIntegerField(editable=False)),
                ('Product_class', models.CharField(editable=False, max_length=20)),
                ('Product_name', models.CharField(editable=False, max_length=20)),
                ('Product_type', models.CharField(blank=True, choices=[('P', 'In'), ('D', 'Nhuộm')], max_length=1, verbose_name='Loại Thành Phẩm:')),
                ('Customer', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('BatchNo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Lần Xuất:')),
                ('BatchID', models.CharField(blank=True, max_length=26, unique=True, verbose_name='Mã Lô')),
                ('Code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã Màu/ Mã Bông:')),
                ('uCode', models.CharField(editable=False, max_length=22)),
                ('Qty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số Lượng (Cây):')),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Khối Lượng:')),
                ('Note', models.CharField(blank=True, max_length=100, verbose_name='Ghi Chú:')),
                ('Created_Time', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('Dye_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Print_Dye', to='QLSanXuat.tay_nhuom', verbose_name='Mã Lô Nhuộm:')),
                ('Print_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Print_Dye', to='QLSanXuat.tay_in', verbose_name='Mã Lô In')),
                ('Stretch_Des', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khocang', verbose_name='Lò Căng:')),
            ],
            options={
                'verbose_name_plural': '1.5. Căng',
            },
        ),
        migrations.AlterUniqueTogether(
            name='det_tay',
            unique_together={('year', 'FromWhere', 'Destination', 'BatchNo')},
        ),
    ]
