# Generated by Django 4.1.6 on 2023-05-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLSanXuat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='det_tay',
            name='RE',
            field=models.BooleanField(default=0, verbose_name='Hàng Trả'),
        ),
        migrations.AlterField(
            model_name='product_class',
            name='Product_class',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phân Loại Hàng:'),
        ),
    ]
