# Generated by Django 4.1.6 on 2023-05-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QLSanXuat', '0002_det_tay_re_alter_product_class_product_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='det_tay',
            unique_together={('year', 'FromWhere', 'Destination', 'BatchNo', 'RE')},
        ),
    ]
