# Generated by Django 4.1.6 on 2023-05-20 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QLSanXuat', '0004_alter_det_tay_fromwhere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_tay',
            name='FromWhere',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khodet', verbose_name='Nơi Đi:'),
        ),
    ]
