# Generated by Django 4.1.6 on 2023-05-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QLSanXuat', '0007_det_tay_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cang',
            name='Creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người Tạo:'),
        ),
        migrations.AlterField(
            model_name='det_tay',
            name='CS',
            field=models.SmallIntegerField(editable=False, verbose_name='Tồn:'),
        ),
        migrations.AlterField(
            model_name='tay_in',
            name='Creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người Tạo:'),
        ),
        migrations.AlterField(
            model_name='tay_nhuom',
            name='Creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người Tạo:'),
        ),
    ]
