# Generated by Django 4.1.6 on 2023-05-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLSanXuat', '0009_tay_in_cs_alter_tay_in_batchid_alter_tay_moc_batchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tay_nhuom',
            name='CS',
            field=models.SmallIntegerField(default=1, editable=False, verbose_name='Tồn:'),
            preserve_default=False,
        ),
    ]
