# Generated by Django 4.1.6 on 2023-06-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLSanXuat', '0010_tay_nhuom_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cang',
            name='Product_class',
            field=models.CharField(editable=False, max_length=20, verbose_name='Loại Hàng'),
        ),
        migrations.AlterField(
            model_name='cang',
            name='Product_name',
            field=models.CharField(editable=False, max_length=20, verbose_name='Tên Hàng'),
        ),
        migrations.AlterField(
            model_name='cang',
            name='uCode',
            field=models.CharField(editable=False, max_length=22, verbose_name='MM/MB'),
        ),
    ]
