# Generated by Django 4.1.6 on 2023-05-19 07:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QLSanXuat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày:')),
                ('year', models.PositiveSmallIntegerField(editable=False)),
                ('PXK', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Phiếu Xuất Kho:')),
                ('Product_Name', models.CharField(max_length=20, verbose_name='Tên Hàng:')),
                ('Product_Type', models.CharField(max_length=20, verbose_name='Loại Hàng:')),
                ('Final_Product', models.CharField(choices=[('M', 'Mộc'), ('N', 'Nhuộm'), ('I', 'In')], max_length=1, verbose_name='Thành Phẩm:')),
                ('Colours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã Màu:')),
                ('Patterns', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã Bông:')),
                ('Qty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số Cây:')),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Khối Lượng:')),
                ('Cut', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trừ Đầu Cây:')),
                ('Net_Weight', models.DecimalField(decimal_places=2, editable=False, max_digits=7, verbose_name='Khối Lượng Bán:')),
                ('Price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Đơn Giá:')),
                ('Amount', models.DecimalField(decimal_places=2, editable=False, max_digits=13, verbose_name='Thành Tiền:')),
                ('Note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ghi Chú:')),
                ('Created_Time', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khachhang', verbose_name='Khách Hàng:')),
            ],
            options={
                'verbose_name_plural': '1.1 Bán Hàng',
            },
        ),
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày:')),
                ('year', models.PositiveSmallIntegerField(editable=False)),
                ('Product_Name', models.CharField(max_length=20, verbose_name='Tên Hàng:')),
                ('Product_Type', models.CharField(max_length=20, verbose_name='Loại Hàng:')),
                ('Final_Product', models.CharField(choices=[('M', 'Mộc'), ('N', 'Nhuộm'), ('I', 'In')], max_length=1, verbose_name='Thành Phẩm:')),
                ('Colours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã Màu:')),
                ('Patterns', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã Bông:')),
                ('Qty', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số Cây:')),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Khối Lượng:')),
                ('Cut', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trừ Đầu Cây:')),
                ('Net_Weight', models.DecimalField(decimal_places=2, editable=False, max_digits=7, verbose_name='Khối Lượng Bán:')),
                ('Price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Đơn Giá:')),
                ('Amount', models.DecimalField(decimal_places=2, editable=False, max_digits=13, verbose_name='Thành Tiền:')),
                ('Note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ghi Chú:')),
                ('Created_Time', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khachhang', verbose_name='Khách Trả:')),
            ],
            options={
                'verbose_name_plural': '1.2 Hàng Khách Trả',
            },
        ),
        migrations.CreateModel(
            name='Customer_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày:')),
                ('year', models.PositiveSmallIntegerField(editable=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Số Tiền Trả:')),
                ('Note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ghi Chú:')),
                ('Created_Time', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khachhang', verbose_name='Khách Hàng:')),
            ],
            options={
                'verbose_name_plural': '1.3 Thanh Toán Của Khách',
            },
        ),
        migrations.CreateModel(
            name='Customer_Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.PositiveSmallIntegerField(default=2022, verbose_name='Năm')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Công Nợ')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='QLSanXuat.khachhang', verbose_name='Khách Hàng')),
            ],
            options={
                'verbose_name_plural': '1.4 Chốt Công Nợ Cuối Năm',
                'unique_together': {('Customer', 'Year')},
            },
        ),
    ]
