# Generated by Django 4.1.6 on 2023-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_pay',
            name='Sync',
            field=models.BooleanField(default=True, editable=False, verbose_name='Đồng Bộ'),
        ),
    ]
