# Generated by Django 4.1.6 on 2023-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_manage', '0002_customer_pay_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_pay',
            name='Sync',
            field=models.BooleanField(editable=False, verbose_name='Đồng Bộ'),
        ),
    ]
