# Generated by Django 4.1.6 on 2023-06-01 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_manage', '0003_alter_customer_pay_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='PXK',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Phiếu Xuất Kho:'),
        ),
    ]
