# Generated by Django 4.1.6 on 2023-04-03 03:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yarn_manage', '0002_delivery_batchid_delivery_batchno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='OrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yarn_manage.yarnorder', verbose_name='Mã Đặt Sợi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kho Về Sợi'),
        ),
        migrations.AlterField(
            model_name='yarnorder',
            name='Creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người Tạo:'),
        ),
        migrations.AlterField(
            model_name='yarnvendor',
            name='Name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tên NBH'),
        ),
        migrations.CreateModel(
            name='YarnPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày:')),
                ('year', models.PositiveSmallIntegerField(editable=False)),
                ('Pay', models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Số Tiền Trả:')),
                ('Deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Phần Cọc:')),
                ('Batch', models.CharField(blank=True, max_length=10, null=True, verbose_name='Theo Lô Hàng:')),
                ('Note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ghi Chú:')),
                ('Created_Time', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='yarn_manage.yarnvendor', verbose_name='Nhà Bán Hàng:')),
            ],
            options={
                'verbose_name_plural': '2.3 Trả Tiền Sợi',
            },
        ),
    ]
