# Generated by Django 4.1.6 on 2023-04-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0005_delivery_payvalue_alter_yarndebt_ly_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yarndebt_ly',
            options={'verbose_name_plural': '2.4 Lưu Công Nợ Cuối Năm'},
        ),
    ]
