# Generated by Django 4.1.6 on 2023-05-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0007_alter_warehouse_address_alter_warehouse_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarntype',
            name='Name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Loại Sợi:'),
        ),
    ]
