# Generated by Django 4.1.6 on 2023-05-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0008_alter_yarntype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarnpay',
            name='Sync',
            field=models.BooleanField(default=False, editable=False),
            preserve_default=False,
        ),
    ]
