# Generated by Django 4.1.6 on 2023-05-23 06:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yarn_manage', '0009_yarnpay_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yarn_manage.warehouse')),
            ],
        ),
        migrations.AlterModelOptions(
            name='yarndebt_ly',
            options={'verbose_name_plural': '2.5 Lưu Công Nợ Cuối Năm'},
        ),
        migrations.AlterModelOptions(
            name='yarnpay',
            options={'verbose_name_plural': '2.4 Trả Tiền Sợi'},
        ),
        migrations.CreateModel(
            name='YarnTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Ngày:')),
                ('year', models.PositiveSmallIntegerField(editable=False)),
                ('YarnType', models.CharField(max_length=10, verbose_name='Loại Sợi:')),
                ('YarnStats', models.CharField(max_length=15, verbose_name='Chỉ Số Sợi:')),
                ('YarnCode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã Sợi:')),
                ('Box_Pack', models.CharField(choices=[('T', 'Thùng'), ('K', 'Kiện')], max_length=1, verbose_name='Quy Cách:')),
                ('BoxQty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Số Thùng/Kiện:')),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Khối Lượng:')),
                ('Note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ghi Chú:')),
                ('Created_Time', models.DateTimeField(auto_now=True)),
                ('Sync', models.BooleanField(editable=False)),
                ('Database', models.CharField(editable=False, max_length=10, null=True)),
                ('Address', models.BigIntegerField(editable=False, null=True)),
                ('Creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người Tạo:')),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='places', to='yarn_manage.warehouse2', verbose_name='Nhập Vào:')),
                ('Origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='places', to='yarn_manage.warehouse', verbose_name='Xuất Đi:')),
            ],
            options={
                'verbose_name_plural': '2.3 Xuất Nhập Sợi',
            },
        ),
    ]
