# Generated by Django 4.1.6 on 2023-05-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0010_warehouse2_alter_yarndebt_ly_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarntransfer',
            name='Destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='places', to='yarn_manage.warehouse', verbose_name='Nhập Vào:'),
        ),
        migrations.AlterField(
            model_name='yarntransfer',
            name='Origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='places', to='yarn_manage.warehouse2', verbose_name='Xuất Đi:'),
        ),
    ]
