# Generated by Django 4.1.6 on 2023-05-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0011_alter_yarntransfer_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarntransfer',
            name='YarnType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='yarn_manage.yarntype', verbose_name='Loại Sợi:'),
        ),
    ]
