# Generated by Django 4.1.6 on 2023-05-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0014_alter_yarntransfer_box_pack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarndebt_ly',
            name='Debt',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Số Tiền:'),
        ),
        migrations.AlterField(
            model_name='yarndebt_ly',
            name='Vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='yarn_manage.yarnvendor', verbose_name='Người Bán:'),
        ),
        migrations.AlterField(
            model_name='yarndebt_ly',
            name='Year',
            field=models.PositiveSmallIntegerField(default=2022, verbose_name='Năm:'),
        ),
        migrations.AlterField(
            model_name='yarntransfer',
            name='Destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='yarn_manage.warehouse', verbose_name='Nơi Đến:'),
        ),
        migrations.AlterField(
            model_name='yarntransfer',
            name='Origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='yarn_manage.warehouse2', verbose_name='Nơi Đi:'),
        ),
    ]
