# Generated by Django 4.1.6 on 2023-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0015_alter_yarndebt_ly_debt_alter_yarndebt_ly_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarnorder',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=12, verbose_name='Thành Tiền:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yarnorder',
            name='Rest_B',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Số Th/K Còn Lại:'),
        ),
        migrations.AddField(
            model_name='yarnorder',
            name='Rest_W',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Khối Lượng:'),
            preserve_default=False,
        ),
    ]
