# Generated by Django 4.1.6 on 2023-05-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0016_yarnorder_amount_yarnorder_rest_b_yarnorder_rest_w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarnorder',
            name='Rest_W',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=9, null=True, verbose_name='Kh/Lượng Còn:'),
        ),
    ]
