# Generated by Django 4.1.6 on 2023-06-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0017_alter_yarnorder_rest_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarndebt_ly',
            name='Buy_In',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Mua Vào:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yarndebt_ly',
            name='Debt_LY',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Nợ Năm Trước:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yarndebt_ly',
            name='Pay_Out',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Bán Ra:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yarnorder',
            name='Rest_B',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Số Th/K Còn Lại:'),
        ),
    ]
