# Generated by Django 4.1.6 on 2023-06-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0018_yarndebt_ly_buy_in_yarndebt_ly_debt_ly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarndebt_ly',
            name='Match',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
