# Generated by Django 4.1.6 on 2023-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarn_manage', '0020_alter_yarnorder_rest_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='WH_Type',
            field=models.CharField(choices=[('D', 'Dệt'), ('S', 'Se')], default=1, max_length=1, verbose_name='Chức Năng:'),
            preserve_default=False,
        ),
    ]
